# fly.toml app configuration file generated for transliteration on 2025-10-28T22:41:52+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'transliteration'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
